name: Auto Merge to Main

on:
  push:
    branches:
      - hakan-third-times-the-charm

# Add explicit permissions block
permissions:
  contents: write

jobs:
  merge-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Ensure we can push to the repo
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
      
      - name: Merge to main
        run: |
          # Get latest changes from the remote
          git fetch origin
          
          # Switch to main branch
          git checkout main
          git pull origin main
          
          # Merge the changes, using --no-ff to create a merge commit
          if git merge --no-ff origin/hakan-third-times-the-charm -m "Auto-merge hakan-third-times-the-charm into main"; then
            # If merge succeeded, push the changes
            git push origin main
            echo "Successfully merged and pushed to main"
          else
            # If there are conflicts, abort the merge and report the failure
            git merge --abort
            echo "Merge conflicts detected. Please resolve conflicts manually."
            exit 1
          fi 